# Generated by Django 3.1.7 on 2021-06-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitaastore', '0002_auto_20210624_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Laptops',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderedproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderedproducts',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderedProducts',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
