# Generated by Django 3.2.4 on 2021-06-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaastore', '0003_auto_20210628_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='processor',
            field=models.CharField(max_length=255),
        ),
    ]
