# Generated by Django 3.2.4 on 2021-06-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaastore', '0004_auto_20210630_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='camera',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='display',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='memory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='storage',
            field=models.CharField(max_length=255),
        ),
    ]
